# Generated by Django 3.2.7 on 2021-09-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210925_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkroom_y',
            name='author',
        ),
        migrations.DeleteModel(
            name='TalkRoom_F',
        ),
        migrations.DeleteModel(
            name='TalkRoom_Y',
        ),
    ]
